- import_playbook: fail2ban.yml
  tags: fail2ban

- hosts: all
  roles:
    - role: geerlingguy.postgresql
      become: yes
  vars:
    postgresql_databases:
      - name: metabase
    postgresql_users:
      - name: metabase
        password: metabase

- import_playbook: metabase.yml
  tags: metabase
