---
- name: Install Metabase
  hosts: webservers
  become: true
  tasks:
    - name: add apt repo
      apt_repository:
        repo: 'ppa:openjdk-r/ppa'
        state: present
    - name: Install Java
      apt:
        name: openjdk-8-jdk
        update_cache: yes
        state: present
    - name: Create dir
      file:
        path: /opt/metabase
        state: directory
        mode: 0755
        owner: ubuntu
    - name: Download metabase
      become: yes
      get_url:
        url: http://downloads.metabase.com/v0.30.4/metabase.jar
        dest: /opt/metabase/metabase.jar
        mode: 0755
    - name: Create backup dir
      file:
        path: /backup
        state: directory
        mode: 0755
        owner: ubuntu
    - name: add env file
      copy:
        src: ../files/metabase-environment
        dest: /etc/metabase-environment
        mode: 0755
    - name: update password
      lineinfile:
        path: /etc/metabase-environment
        regexp: '^MB_DB_PASS='
        line: MB_DB_PASS="{{ MB_DB_PASS }}"
    - name: add metabase to service
      copy:
        src: ../files/metabase.service
        dest: /etc/systemd/system/metabase.service
        mode: 0755
    - name: start metabase
      systemd:
        name: metabase
        state: restarted
        enabled: True
