---
- name: Install Mysql
  hosts: webservers
  become: true
  tasks:
    - apt:
        name: mysql-server
        state: present
    - systemd:
        name: mysql
        state: restarted
        enabled: True
    - apt:
        name: libmysqlclient-dev
        state: present
    - apt:
        name: python-pip
        state: present
    - pip:
        name: MySQL-python
    - name: Create a new database with name 'metabase'
      mysql_db:
        name: metabase
        encoding: utf8
        state: present
    - mysql_user:
        name: metabase
        password: "{{ MB_DB_PASS }}"
        host: '%'
        priv: '*.*:ALL'
        state: present
    - ini_file:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        section: mysqld
        option: bind-address
        value: localhost
    - systemd:
        name: mysql
        state: restarted
        enabled: True
