---
- name: Install Mysql
  hosts: all
  become: true
  tasks:
    - apt:
        name:
          - mysql-server
          - libmysqlclient-dev
          - python3-pip
        state: present
        update_cache: yes
    - pip:
        name: MySQL-python
    - systemd:
        name: mysql
        state: restarted
        enabled: True
    - name: Create a new database with name 'metabase'
      mysql_db:
        name: metabase
        encoding: utf8
        state: present
    - mysql_user:
        name: metabase
        password: metabase
        host: '%'
        priv: '*.*:ALL'
        state: present
    - ini_file:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        section: mysqld
        option: bind-address
        value: localhost
    - systemd:
        name: mysql
        state: restarted
        enabled: True
